/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package androidx.recyclerview;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int alpha = 0x7f030028;
        public static final int coordinatorLayoutStyle = 0x7f0300ad;
        public static final int fastScrollEnabled = 0x7f0300df;
        public static final int fastScrollHorizontalThumbDrawable = 0x7f0300e0;
        public static final int fastScrollHorizontalTrackDrawable = 0x7f0300e1;
        public static final int fastScrollVerticalThumbDrawable = 0x7f0300e2;
        public static final int fastScrollVerticalTrackDrawable = 0x7f0300e3;
        public static final int font = 0x7f0300e7;
        public static final int fontProviderAuthority = 0x7f0300e9;
        public static final int fontProviderCerts = 0x7f0300ea;
        public static final int fontProviderFetchStrategy = 0x7f0300eb;
        public static final int fontProviderFetchTimeout = 0x7f0300ec;
        public static final int fontProviderPackage = 0x7f0300ed;
        public static final int fontProviderQuery = 0x7f0300ee;
        public static final int fontStyle = 0x7f0300ef;
        public static final int fontVariationSettings = 0x7f0300f0;
        public static final int fontWeight = 0x7f0300f1;
        public static final int keylines = 0x7f030121;
        public static final int layoutManager = 0x7f030126;
        public static final int layout_anchor = 0x7f030127;
        public static final int layout_anchorGravity = 0x7f030128;
        public static final int layout_behavior = 0x7f030129;
        public static final int layout_dodgeInsetEdges = 0x7f030155;
        public static final int layout_insetEdge = 0x7f03015e;
        public static final int layout_keyline = 0x7f03015f;
        public static final int reverseLayout = 0x7f0301a3;
        public static final int spanCount = 0x7f0301bc;
        public static final int stackFromEnd = 0x7f0301c3;
        public static final int statusBarBackground = 0x7f0301ca;
        public static final int ttcIndex = 0x7f030231;
    }
    public static final class color {
        private color() {}

        public static final int notification_action_color_filter = 0x7f050090;
        public static final int notification_icon_bg_color = 0x7f050091;
        public static final int ripple_material_light = 0x7f05009f;
        public static final int secondary_text_default_material_light = 0x7f0500a1;
    }
    public static final class dimen {
        private dimen() {}

        public static final int compat_button_inset_horizontal_material = 0x7f060053;
        public static final int compat_button_inset_vertical_material = 0x7f060054;
        public static final int compat_button_padding_horizontal_material = 0x7f060055;
        public static final int compat_button_padding_vertical_material = 0x7f060056;
        public static final int compat_control_corner_material = 0x7f060057;
        public static final int compat_notification_large_icon_max_height = 0x7f060058;
        public static final int compat_notification_large_icon_max_width = 0x7f060059;
        public static final int fastscroll_default_thickness = 0x7f06008a;
        public static final int fastscroll_margin = 0x7f06008b;
        public static final int fastscroll_minimum_range = 0x7f06008c;
        public static final int item_touch_helper_max_drag_scroll_per_frame = 0x7f060094;
        public static final int item_touch_helper_swipe_escape_max_velocity = 0x7f