/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package androidx.transition;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int alpha = 0x7f030028;
        public static final int font = 0x7f0300e7;
        public static final int fontProviderAuthority = 0x7f0300e9;
        public static final int fontProviderCerts = 0x7f0300ea;
        public static final int fontProviderFetchStrategy = 0x7f0300eb;
        public static final int fontProviderFetchTimeout = 0x7f0300ec;
        public static final int fontProviderPackage = 0x7f0300ed;
        public static final int fontProviderQuery = 0x7f0300ee;
        public static final int fontStyle = 0x7f0300ef;
      