/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.google.android.gms.base;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int buttonSize = 0x7f03005b;
        public static final int circleCrop = 0x7f030080;
        public static final int colorScheme = 0x7f030098;
        public static final int imageAspectRatio = 0x7f03010e;
        public static final int imageAspectRatioAdjust = 0x7f03010f;
        public static final int scopeUris = 0x7f0301a8;
    }
    public static final class color {
        private color() {}

        public static final int common_google_signin_btn_text_dark